### PR TITLE
* Added Animations to XLong Ponytail & Tied Back + More

### PR DESCRIPTION
**Pull request by jrconway3**
Performed the Following:
1. Added Animations to XLong Ponytail and Tied Back (the bangs)
2. Fixed Issues With Some Hair Extensions
3. Added Alternate Animations (Sit/Run/Jump/Idle) to These Hairstyles

Previously I was unable to add the alternate (non-universal) hairstyles because the PR open page kept freezing on me. Still did, but I finally managed to create the PR somehow...

### CODE REVIEW

**Comment by jrconway3** [comment]
Weird, not sure how that happened. I'll check it out.

**Comment by jrconway3** [comment]
I tried to resolve the conflict but it doesn't seem to have resolved itself.

**Comment by sanderfrenken** [comment]
> I tried to resolve the conflict but it doesn't seem to have resolved itself.

that sucks, but you need to resolve it in order to be able to merge the PR. Alternatively, you can create a new PR from master with the changes.

**Comment by jrconway3** [comment]
Yeah it seems like that's what I'll have to do. So I have to remember everything I included...

**Pull request closed without merging**
