### PR TITLE
Issue #141 Mapped All LPC Revised Hairstyles to Expanded Universal

### PR DESCRIPTION
**Pull request by jrconway3**
Mapped all LPC revised Hairstyles to all frames on ULPC:

Some hairstyles I ignored the LPC Revised assets and only used these ones, and some hairstyles here don't exist on ULPC at all, so there's at least two new hairstyles present.

I dropped male/female distinctions, but this might be a mistake... the problem is when the body model adjusts in size. Granted, using the female assets should be fine as it just means some parts of the hair will be over the "thick" male body, which Eliza doesn't even have. Having the hair go over the body in some instances is probably better than having open gaps by using the male versions, so maybe this will be fine.

### CODE REVIEW

**Comment by jrconway3** [comment]
I also have this PR: https://github.com/jrconway3/Universal-LPC-Spritesheet-Character-Generator/pull/4

I can forward it to master if this one gets merged, but that branch extends off of this one unfortunately.

**Comment by jrconway3** [comment]
I messed this up a bit because I started working on doing clothes but switched over to hairstyles. So I started adjusting the clothing directories to handle variants of specific types of shirts (longsleeve, shortsleeve, sleeveless, etc) and never finished handling the shirts yet. So I fixed moving assets around without replacing them for now. I'll add the new assets later ASAP with a new PR, but for now this just adjusts the directories for clothes in preparation for these updates, and otherwise adds hairstyles.

**Comment by sanderfrenken** [comment]
> Mapped all LPC revised Hairstyles to all frames on ULPC:
> 
> Some hairstyles I ignored the LPC Revised assets and only used these ones, and some hairstyles here don't exist on ULPC at all, so there's at least two new hairstyles present.
> 
> I dropped male/female distinctions, but this might be a mistake... the problem is when the body model adjusts in size. Granted, using the female assets should be fine as it just means some parts of the hair will be over the "thick" male body, which Eliza doesn't even have. Having the hair go over the body in some instances is probably better than having open gaps by using the male versions, so maybe this will be fine.

You are on fire! Very awesome what you are doing last period :)

I am not sure either about dropping the male/ female distinctions. I guess there was a valid reason for having them, and using lpc-tools the generation of the assets was automated. I hope/ think bluecarrot can shed some light on this, I will ask his opinion as well. Maybe, we can have lpc tools to be capable of generating the hair frames as well for the new extended LPC layout for example.

The fact that the "thick" male body is not supported by Eliza doesn't resonate with me as an argument to align more to a different way of working than before. 
I'd say that adding her animation and adopting her assets to the (extended)ULPC sheets is very useful and legit. 

But changing existing assets to revised should be done very carefully, in order to not break the current much more extensive ULPC assets that are present in this repo. 

I will ask bluecarrot if he is able to reply here!

**Comment by jrconway3** [comment]
"The fact that the "thick" male body is not supported by Eliza doesn't resonate with me as an argument to align more to a different way of working than before."

I didn't say this was an argument to remove them. I just want to clarify here:

I did this because I forgot that there are some instances where there might be legitimate distinctions. Because this is a concern I'll go back and double-check to make sure the male assets aren't that different.

However, if you check Eliza's assets:
https://github.com/ElizaWy/LPC/tree/main/Characters/Body

You can see here that the bodies she's using are labeled "Feminine, Thin" and "Masculine, Thin".

I think her intent was clearly to eventually add the thicker male body model as well, she just never got around to doing so yet. So its not like she didn't intend on using it.


This isn't about Eliza, this is about me. I just legitimately forgot to check both styles and make sure there weren't differences between male and female, I made an assumption.

Now, I should note: a good chunk of these SHOULD be fine anyway. Any hairstyles that don't have anything going below the neckline should be identical anyway and frankly, I don't see the point in keeping split between "male" and "female" because these assets should be exactly the same. I will double-check the ones that are longer and do go below the neckline, though. Those are the main areas to look into. What I can do there is cut them out around the body, however, I'll cut them out around the female head.

Because of the fact that the heads are no longer part of the body, we _cannot_ make distinctions for hair along the heads anymore. (In fact, this is the main reason why I didn't think to check; because the heads are distinct now, I was assuming that the male/female split hairstyles was an old redundancy.)

**Comment by jrconway3** [comment]
So I'll just start listing off assets that are identical between the two. All these are based on female, so I just need to compare them to "male". IMO, if the assets are identical I see no reason to keep separate lists of assets, we're just creating redundancies at this point.

Short hairstyles:
Balding is identical (however, I fixed a few frames on the "down" animation where where hairline was off a bit).
Flat Top is identical (however, I missed "climb", so I need to re-include this one again with the fix)

**Comment by jrconway3** [comment]
"Maybe, we can have lpc tools to be capable of generating the hair frames as well for the new extended LPC layout for example."

When I tried using lpctools to run the command to "rearrange" to all frames, my ears did not map correctly at all. So I gave up on using lpctools for the rearrange command and currently only use it for palettes. I have been having a PITA time getting lpctools to work in general, so maybe if bluecarrot could help that'd be appreciated.

**Comment by sanderfrenken** [comment]
Clear story, I know it's not about Eliza! Just want to make sure we don't break existing assets, and with all the work we did in the last years I sort of lost track here and there about why we have certain setups.

`(In fact, this is the main reason why I didn't think to check; because the heads are distinct now, I was assuming that the male/female split hairstyles was an old redundancy.)`

Yes I hope you are right about this indeed, that it's an old redundancy. That would allow a lot of cleanup as you did in this PR already, and save a lot of work for the future.

I dropped the question with bluecarrot, I hope he can reply. He did a lot of the hairstyles that are in the repo, so if there is anything to worry about, he would know :)

**Comment by jrconway3** [comment]
"I'd say that adding her animation and adopting her assets to the (extended)ULPC sheets is very useful and legit."

Just to clarify here: I have only used Eliza's versions if the assets were identical to what's already on ULPC. Some of these hairstyles have different sizes because Eliza is using smaller heads. In these cases I did NOT use her versions in order to keep things consistent.

**Comment by sanderfrenken** [comment]
`When I tried using lpctools to run the command to "rearrange" to all frames, my ears did not map correctly at all. So I gave up on using lpctools for the rearrange command and currently only use it for palettes. I have been having a PITA time getting lpctools to work in general, so maybe if bluecarrot could help that'd be appreciated.`

I got it working once, but setting it up with all the python libs also was painful to me. I am not that knowledgeable on the python stack :( As this repo already requires node, I thought of creating some useful tooling in JS. But yeah, priorities..

**Comment by jrconway3** [comment]
- Flat Top Fade looks good
- Natural I lowered the final "down" frame by one to make it line up better. Otherwise this is identical.
- Cowlick is identical
- Parted 2 is new so irrelevant
- Buzzcut I adjusted all the down frames; the first couple of "down" frames typically should be the same as idle, then as you descend the hairline becomes more visible until the end when its the back side flipped vertically; I've noticed a few hairstyles where this problem existed, and because I was working on it anyway I made these fixes for consistency. However, the two hairstyles are identical between male and female.
- Curly 2 is also new and I don't see any areas where it would cross over with the body


So as I figured, all the "short" hairstyles should be fine here. Its the "Medium" hairstyles where we might have more issues.

**Comment by jrconway3** [comment]
Okay, this one I think its possible we might want to do something else with, but its hit or miss:

Page 2 is identical between male or female. That's not the issue.

The issue is that I stuck with Eliza's here because it has an extra palette color that's slightly lighter along the bangs (page2 presumably was either made before the lighter palette was added, or whoever did make it just didn't use this extra color; I did the same thing with my earlier hairstyles where I forgot to add an extra lighter color). Should we just keep both versions instead of replacing it? The difference isn't THAT big, but it is notable.

Apparently I also lowered the entire hairstyle down by one pixel to mesh to the head better. Perhaps it should remain at its original position.

Old:
ulpccg-page2-old

New:
ulpccg-page2-revised

**Comment by jrconway3** [comment]
For the rest:
- Curly Short is identical between male/female, however, again I did replace the first two "down" frames. I also removed a part of the hair from over the top of the arm on the fourth-to-last "south" shoot animation, but looking it over, I think I'll just restore the old one there. I think there's a reason why this was done that way and it makes sense.
- Idol looks fine
- Bangs & Bun looks fine
- Bob looks fine
- Cornrows looks fine
- Dreadlocks Short looks fine
- Twists Straight and Fade look fine


All right, so looking it over, I think these hairstyles simply aren't long enough to have notable differences between male/female. There's some potential problem areas, but this isn't one of them. I will be more careful going forward, though, so we do keep the differences for the male bodies. At least for existing assets (for new assets I create I might not make a distinction).

I think the only potential concern right now is "Page 2" which has notable differences between the two versions. Let me know how that looks, I can turn it into "Page 3" and keep the old one if preferred.

**Comment by sanderfrenken** [comment]
> Okay, this one I think its possible we might want to do something else with, but its hit or miss:
> 
> Page 2 is identical between male or female. That's not the issue.
> 
> The issue is that I stuck with Eliza's here because it has an extra palette color that's slightly lighter along the bangs (page2 presumably was either made before the lighter palette was added, or whoever did make it just didn't use this extra color; I did the same thing with my earlier hairstyles where I forgot to add an extra lighter color). Should we just keep both versions instead of replacing it? The difference isn't THAT big, but it is notable.
> 
> Apparently I also lowered the entire hairstyle down by one pixel to mesh to the head better. Perhaps it should remain at its original position.
> 
> Old: ulpccg-page2-old
> 
> New: ulpccg-page2-revised

I see the difference, minimal but it's there indeed. Id propose to just use the new one, and remove the old one. its too small of a diff to keep both IMO

Thanks a lot again for sorting this all out, awesome!

**Comment by sanderfrenken** [comment]
I think you already only have the new parted in here atm, let me know if that is correct indeed. then I will approve and merge.

Bluecarrot didn't get back to me yet, but I am 99% sure your PR should be ok (and is a great addition obviously). If not, we always can revert/ adjust later again :)

**Comment by jrconway3** [comment]
Parted 2 is new (I called it 2 because its a new version of Parted by ElizaWy that's not here, but its not the same as the original Parted either), but that reminds me I forgot to add the credits. I'll fix the conflict and credits.

I need to add ElizaWy to all hairstyles where she did animations as well.

**Comment by jrconway3** [comment]
In addition to fixing the conflicts I also fixed a few placement issues with "Natural". If any more issues show up those can be fixed as well.

I already noticed that some of the ears have wrong placement on certain frames, I'll have to fix that later.

**Comment by sanderfrenken** [comment]
Lets merge! Nice job man

**Pull request merged**
