### PR TITLE
* Added Alt Actions for Wings

### PR DESCRIPTION
**Pull request by jrconway3**
Related to this issue:
https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/issues/88

I'm going to try and keep adding as many of these assets as possible so that eventually there will be enough to add these alternate animations.

This adds run (both base run and Eliza's revised run), jump, and idle animations for the wings. I also added the release on OGA (https://opengameart.org/content/lpc-new-wing-animations-original-by-elizawy) as well as a link to Eliza's repo for the original wing assets to the credits.

### CODE REVIEW

**Comment by sanderfrenken** [comment]
I think it would be really nice to add the alternative animations (jump, climb, idle etc) as well. 

The form of how to do this though, that is to be determined.
I think we should start with the body sheets. Using the custom animation handler however, is too slow. Moreover, the custom animation handler is meant for reusing existing animation frames in a new sequence combined with an accessoire sheet that fits it (like a backward slash animation).

Therefore, as these new animations are in fact new frames I think the most efficient way would be to add them to the universal sheet. 

As such, adding the loose animation sheets as done here will not serve the purpose.

What do you think?

**Comment by sanderfrenken** [comment]
Btw I know you added them for some other sheets already, that is fine: we can clean that up if we go in the universal sheet direction. First we need a strategy:)

**Comment by sanderfrenken** [comment]
Plus.. Lets move the discussion to the issue about this topic :)

**Comment by jrconway3** [comment]
I opened a new PR with the idea in mind of expanding the main sheet instead. In my testing, it appears that expanding the main sheet works fine even when individual asset sheets don't have the full size, so we can deploy that without breaking anything else, and gradually fill out new assets for these sheets. Then we can open up issues on a case-by-case basis for various pieces.

**Pull request closed without merging**
