### PR TITLE
Issue 88 Added All Four Tails to All Frames, Child and Adult

### PR DESCRIPTION
**Pull request by jrconway3**
Added all tails to all frames, both child and adult.

1. My furry tails were fairly easy for child as they were already mapped.
2. I had to map some new animations for the combat animations, but I just reused existing frames.
3. Some "side" tail frames appear in the "front" rather than the back, such as on some run animations and a few combat animations. I feel like maybe I should have a third layer for these, with these assets only BARELY appearing in front of the body.
4. The lizard tails I added some new animations for, mostly lifting the tail up a bit.
5. Some lizard tails appear in the front as well with a lighter color (mostly on jump, some combat animations and some run animations).
6. Added lizard tails to child as well, these previously weren't on child to my knowledge.
7. Added alternate color lizard tails if you want to have lizard tails that aren't meshed to the body color. I thought this would look okay but tbh it kinda doesn't, though it would probably look better if you added clothes. The tails were designed to be direct extensions of the body after all.

### CODE REVIEW

**Review by sanderfrenken — APPROVED** [review]

**Comment by fnaith** [comment]
Just mention it, all folder path in `sheet_definitions\tail_cat.json'  don't end with '/'.

Ex. `"male" : "body/tail/cat/adult/fg",` was beening `"male" : "body/tail/cat/universal/adult_front/",`

* Update : Also, variant name seems to be changed from underscore to space.

**Comment by jrconway3** [comment]
I swear I tested all these locally before opening the PR. *sigh*

**Comment by jrconway3** [comment]
I'll fix it in the next update lol

**Comment by fnaith** [comment]
Thanks you ~~~

**Pull request merged**
