### PR TITLE
* Issue #205 Added Plate Armour to All Frames

### PR DESCRIPTION
**Pull request by jrconway3**
This took me all weekend basically to complete, so it wasn't exactly easy. Still, we have SOME armor on new assets now:

Issue #205 and #202:
* Added Plate Armour to Idle, Combat Idle, Jump, Sit, Emotes, Run, and Revised Combat
* Added "Teen" Variant to All Frames

As an extra, I noticed the license wasn't up-to-date on body armour:
* Issue #142 Added OGA-BY to Body Armour Assets
* Nilla122 and Wulax both added OGA-BY to their assets

### CODE REVIEW

**Comment by jrconway3** [comment]
I may need to tweak this a bit. I accidentally had some bad head overlays in place, so the neck is missing a few pieces on some of the new frames *sigh*

**Comment by jrconway3** [comment]
Yeah I had the Male and Female heads enabled at the same time. I made sure it worked on Female specifically. On Male they looked fine, but there were gaps when I disabled Male Heads and it didn't look great.

**Comment by jrconway3** [comment]
I keep finding new things... now I notice a weird inconsistency on south backslash; the armour suddenly "appears" lower on the leg on frame 7.

**Comment by jrconway3** [comment]
This should be ready now. Sorry for the multiple updates.

**Review by sanderfrenken — APPROVED** [review]

**Pull request merged**
